[package]
name = "equivalent"
version = "1.1.0"
rust-version = "1.28"
license = "Apache-2.0 OR MIT"
description = "Traits for key comparison in maps."
repository = "https://github.com/indexmap-rs/equivalent"
keywords = ["hashmap", "no_std"]
categories = ["data-structures", "no-std"]
